version: '3.1'

services:
  nova-api:
    container_name: "nova-api"
    image: nova/nova-api
    build:
      dockerfile: ../nova.api/docker/Dockerfile.prod
      context: ../nova.api
    working_dir: /app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8002:8001"
    volumes:
      - ../nova-api-upload:/app/upload
    networks:
      - nova_network
  nova-web:
    container_name: "nova-web"
    image: nova/nova-web
    build:
      context: ../nova.web
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: always
    environment:
      PORT: 80
    ports:
      - "4201:80"
    networks:
      - nova_network

  nova-web-cloud:
    container_name: "nova-web-cloud"
    image: nova/nova-web-cloud
    build:
      context: ../nova.web
      dockerfile: ./Dockerfile.cloud
    working_dir: /app
    restart: always
    environment:
      PORT: 80
    ports:
      - "4202:80"
    networks:
      - nova_network

  sql_server_express_nova:
    container_name: "sql_server_express_nova"
    restart: always
    image: mcr.microsoft.com/mssql/server:2017-latest
    env_file:
      - ./sql_server.env
    ports:
      - "1433:1433"
    volumes:
      - ../db:/var/opt/mssql/data
    networks:
      - nova_network
networks:
  nova_network:
    ipam:
      driver: bridge
      config:
        - subnet: "172.19.0.0/16"


