version: '3.1'

services:

  sql_server_express_nova:
    container_name: "sql_server_express_nova"
    restart: always
    image: mcr.microsoft.com/mssql/server:2017-latest
    env_file:
      - ./sql_server.env
    ports:
      - "1433:1433"
    volumes:
      - ../db:/var/opt/mssql/data
    networks:
      - nova_api_network
networks:
  nova_api_network:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"


#  api:
#    container_name: "nova-api"
#    build:
#      context: ../nova-api
#      dockerfile: ./Dockerfile
#    working_dir: /app
#    env_file:
#      - ./nova-api.env
#    ports:
#      - "8002:8001"
#    networks:
#      - nova_api_network
